logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:5001/uaa/users/current
#      token-info-uri: http://localhost:5001/uaa/oauth/check_token

spring:
  profiles:
    active: production
